### PR TITLE
Adding dataset description to UI

### PR DESCRIPTION
**Pull request by kylehamilton**
Included framework for full citation but I want to check with the rest of the team before I do this since it wasn't in the issue #108

### CODE REVIEW

**Comment by shotsuji** [comment]
Hi Kyle,
sounds good - why don't you include it and if it looks too bulky/distracting we comment it out again?

**Comment by kylehamilton** [comment]
Sounds good will do!

**Comment by kylehamilton** [comment]
Sounds good, I've included the dataset citation in the shiny app

**Comment by christinabergmann** [comment]
Curious to see how it looks, but it shouldn't break anything.

**Pull request merged**
